name: deploy
on:
  push:
    branches: [master]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
      - name: build artifacts
        run: composer run build
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: build assets
        run: |
          npm install
          npm start
      - name: Clean up development files
        run: |
          rm -rf .git .github node_modules tests .vscode .dockercontainer .devcontainer
          rm -f *.md app/*.neon app/*.xml *.yml app/router.php package* .dockerignore Dockerfile jsconfig.json vite.config.js
          rm -rf app/scripts app/styles app/routes
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./htdocs/
